apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tha-dev-transaction-gateway
resources:
  - ../../base
  - virtual-service.yaml
helmCharts:
  - name: webapp
    releaseName: transaction-gateway-api
    namespace: tha-dev-transaction-gateway
    version: 0.0.29
    repo: https://swiss-digital-assets-institute.github.io/helm-charts
    additionalValuesFiles:
      - ../../../../values/globals/values.yaml
      - ../../../../values/envs/dev/values.yaml
      - ../../../../values/clusters/tha-dev-che-eks/values.yaml
    valuesInline:
      name: "transaction-gateway-api"
      image:
        repository: 009160051778.dkr.ecr.eu-central-2.amazonaws.com/tha-dev-transaction-gateway-api
        tag: 71682ac2
      autoscaling:
        enabled: true
        minReplicas: 2
        maxReplicas: 5
      quota:
        enabled: false
      istio:
        virtualServices:
          public: true
      monitoring:
        serviceMonitor:
          enabled: true
          extraPort:
            enabled: true
      service:
        port:
          targetPort: 3000
      container:
        port: 3000
      envs:
        - name: ENV
          value: development
        - name: OTEL_SERVICE_NAME
          value: transaction-gateway
        - name: OTEL_ENDPOINT
          value: http://otel-collector.observability.svc.cluster.local:4318/v1/traces
        - name: OTEL_METRICS_PORT
          value: 9090
      resources:
        limits:
          cpu: 500m
          memory: 1024Mi
        requests:
          cpu: 200m
          memory: 512Mi
      livenessProbe:
        enabled: true
        path: /v1/health
        initialDelaySeconds: 30
        periodSeconds: 15
        timeoutSeconds: 10
        successThreshold: 1
        failureThreshold: 6
      readinessProbe:
        enabled: true
        path: /v1/health
        initialDelaySeconds: 30
        periodSeconds: 5
        timeoutSeconds: 3
        successThreshold: 1
        failureThreshold: 3
      externalSecrets:
        enabled: true
        secretStoreRef:
          name: vault-backend
        secrets:
          - secretKey: API_KEY
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/api
              property: API_KEY
          - secretKey: AWS_ACCESS_KEY_ID
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/api
              property: AWS_ACCESS_KEY_ID
          - secretKey: AWS_SECRET_ACCESS_KEY
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/api
              property: AWS_SECRET_ACCESS_KEY
          - secretKey: AWS_COGNITO_APP_CLIENT_ID
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/api
              property: AWS_COGNITO_APP_CLIENT_ID
          - secretKey: AWS_COGNITO_USER_POOL_ID
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/api
              property: AWS_COGNITO_USER_POOL_ID
          - secretKey: AWS_REGION
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/api
              property: AWS_REGION
          - secretKey: DATABASE_URL
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/api
              property: DATABASE_URL
          - secretKey: DS_API_KEY
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/api
              property: DS_API_KEY
          - secretKey: DS_API_URL
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/api
              property: DS_API_URL
          - secretKey: HASHGRAPH_MIRROR_NODE_URL
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/api
              property: HASHGRAPH_MIRROR_NODE_URL
          - secretKey: HASHGRAPH_NETWORK
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/api
              property: HASHGRAPH_NETWORK
          - secretKey: SERVICE_FEE_MARGIN
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/api
              property: SERVICE_FEE_MARGIN
          - secretKey: SES_SENDER
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/api
              property: SES_SENDER
          - secretKey: VAULT_API_URL
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/api
              property: VAULT_API_URL
          - secretKey: VAULT_APP_ROLE_ID
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/api
              property: VAULT_APP_ROLE_ID
          - secretKey: VAULT_APP_ROLE_SECRET_ID
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/api
              property: VAULT_APP_ROLE_SECRET_ID
          - secretKey: SQS_QUEUE_URL
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/api
              property: SQS_QUEUE_URL
          - secretKey: VALIDATION_CLOUD_MIRRORNODE_URL
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/api
              property: VALIDATION_CLOUD_MIRRORNODE_URL
          - secretKey: VALIDATION_CLOUD_API_KEY
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/api
              property: VALIDATION_CLOUD_API_KEY

  - name: webapp
    releaseName: transaction-gateway-cron
    namespace: "tha-dev-transaction-gateway"
    version: 0.0.29
    repo: https://swiss-digital-assets-institute.github.io/helm-charts
    valuesInline:
      name: "transaction-gateway-cron"
      namespace:
        enabled: false
      global:
        env: dev2
      podAnnotations:
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
      image:
        repository: 009160051778.dkr.ecr.eu-central-2.amazonaws.com/tha-dev-transaction-gateway-cron
        tag: 71682ac2
      autoscaling:
        enabled: false
      quota:
        enabled: false
      istio:
        virtualServices:
          enabled: false
      service:
        port:
          targetPort: 3000
      container:
        port: 3000

      envs:
        - name: ENV
          value: development
        - name: OTEL_SERVICE_NAME
          value: transaction-gateway-cron
        - name: OTEL_ENDPOINT
          value: http://otel-collector.observability.svc.cluster.local:4318/v1/traces
      resources:
        limits:
          cpu: 500m
          memory: 1024Mi
        requests:
          cpu: 200m
          memory: 256Mi
      livenessProbe:
        enabled: true
        path: /v1/health
        initialDelaySeconds: 30
        periodSeconds: 15
        timeoutSeconds: 10
        successThreshold: 1
        failureThreshold: 6
      readinessProbe:
        enabled: true
        path: /v1/health
        initialDelaySeconds: 30
        periodSeconds: 5
        timeoutSeconds: 3
        successThreshold: 1
        failureThreshold: 3
      monitoring:
        serviceMonitor:
          enabled: true
          extraPort:
            enabled: true
      externalSecrets:
        enabled: true
        secretStoreRef:
          name: vault-backend
        secrets:
          - secretKey: AWS_ACCESS_KEY_ID
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/cron
              property: AWS_ACCESS_KEY_ID
          - secretKey: AWS_REGION
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/cron
              property: AWS_REGION
          - secretKey: AWS_SECRET_ACCESS_KEY
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/cron
              property: AWS_SECRET_ACCESS_KEY
          - secretKey: BALANCE_TARGET
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/cron
              property: BALANCE_TARGET
          - secretKey: BALANCE_THRESHOLD
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/cron
              property: BALANCE_THRESHOLD
          - secretKey: COGNITO_ADMIN_GROUP_NAME
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/cron
              property: COGNITO_ADMIN_GROUP_NAME
          - secretKey: COGNITO_USER_POOL_ID
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/cron
              property: COGNITO_USER_POOL_ID
          - secretKey: DS_DATABASE_URL
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/cron
              property: DS_DATABASE_URL
          - secretKey: HASHGRAPH_NETWORK
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/cron
              property: HASHGRAPH_NETWORK
          - secretKey: MTG_DATABASE_URL
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/cron
              property: MTG_DATABASE_URL
          - secretKey: SES_SENDER
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/cron
              property: SES_SENDER
          - secretKey: VAULT_API_URL
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/cron
              property: VAULT_API_URL
          - secretKey: VAULT_APP_ROLE_ID
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/cron
              property: VAULT_APP_ROLE_ID
          - secretKey: VAULT_APP_ROLE_SECRET_ID
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/cron
              property: VAULT_APP_ROLE_SECRET_ID
          - secretKey: SQS_QUEUE_URL
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/cron
              property: SQS_QUEUE_URL
          - secretKey: REFILLER_THRESHOLD_BALANCE
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/cron
              property: REFILLER_THRESHOLD_BALANCE

  - name: webapp
    releaseName: transaction-gateway-cli
    namespace: "tha-dev-transaction-gateway"
    version: 0.0.29
    repo: https://swiss-digital-assets-institute.github.io/helm-charts
    additionalValuesFiles:
      - ../../../../values/globals/values.yaml
      - ../../../../values/envs/dev/values.yaml
      - ../../../../values/clusters/tha-dev-che-eks/values.yaml
    valuesInline:
      name: "transaction-gateway-cli"
      namespace:
        enabled: false
      image:
        repository: 009160051778.dkr.ecr.eu-central-2.amazonaws.com/tha-dev-transaction-gateway-cli
        tag: 71682ac2
      autoscaling:
        enabled: false
      quota:
        enabled: false
      istio:
        virtualServices:
          enabled: false
      service:
        port:
          targetPort: 3000
      container:
        port: 3000
      envs:
        - name: ENV
          value: development
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 200m
          memory: 256Mi
      livenessProbe:
        enabled: false
      readinessProbe:
        enabled: false
      monitoring:
        serviceMonitor:
          enabled: false
      externalSecrets:
        enabled: true
        secretStoreRef:
          name: vault-backend
        secrets:
          - secretKey: VAULT_API_URL
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/cli
              property: VAULT_API_URL
          - secretKey: VAULT_APP_ROLE_ID
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/cli
              property: VAULT_APP_ROLE_ID
          - secretKey: VAULT_APP_ROLE_SECRET_ID
            remoteRef:
              key: secrets/tha-dev-che-eks/dev/transaction-gateway/cli
              property: VAULT_APP_ROLE_SECRET_ID

  - name: vault
    includeCRDs: true
    releaseName: vault
    namespace: tha-dev-transaction-gateway
    version: "0.28.1"
    repo: https://helm.releases.hashicorp.com
    valuesInline:
      fullnameOverride: vault
      injector:
        enabled: false
      server:
        annotations:
          proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
        serviceAccount:
          create: true
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::009160051778:role/tha-dev-transaction-gateway-vault
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 256Mi
            cpu: 250m
        dataStorage:
          enabled: false
        standalone:
          enabled: true
          config: |
            ui = true
            listener "tcp" {
              address= "0.0.0.0:8200"
              tls_disable = 1
            }
            seal "awskms" {
              max_lease_ttl = "8760h"
            }
            storage "s3" {}
          disruptionBudget:
            enabled: true
            maxUnavailable: 1
        extraEnvironmentVars:
          AWS_REGION: eu-central-2
          AWS_S3_BUCKET: tha-dev-transaction-gateway-vault
          VAULT_AWSKMS_SEAL_KEY_ID: 9c55dd4d-ed55-484f-8fbb-80ebadbba828