name: Build and Push 📦

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment"
        required: false
        type: string
    secrets:
      env_vars:
        description: "Environment variables for .env file"
        required: false

jobs:
  build-and-push:
    name: Build and Push 📦
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Generate .env file
        run: echo ${{ secrets.env_vars }} > env

      - name: Upload .env as artifact
        uses: actions/upload-artifact@v3
        with:
          name: env-file
          path: env

