name: 'Template For Docker Build, ECR Push And Helm Deploy Actions'

on:
  workflow_call:

    inputs:
      environment:
        type: string
        required: true
      app:
        type: string
        required: true
      ingress-hostname:
        type: string
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      VAULT_ADDR:
        required: true
      VAULT_TOKEN:
        required: true
      TS_OAUTH_CLIENT_ID:
        required: true
      TS_OAUTH_SECRET:
        required: true
      EKS_ENDPOINT:
        required: true
      EKS_SA_SECRET:
        required: true

jobs:

  docker-build-and-push:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

  eks-helm-deploy:

    runs-on: ubuntu-latest
    needs: docker-build-and-push
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4