name: 'Template For Docker Build, ECR Push And Helm Deploy Actions'

on:
  workflow_call:

    inputs:
      environment:
        type: string
        required: true
    secrets:
      NEXT_PUBLIC_APP_URL:
        required: false
      NEXT_PUBLIC_API_URL:
        required: false

jobs:

  docker-build-and-push:

    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check website three times
        run: |
          for i in {1..3}; do
            echo "Checking https://google.com (attempt $i)"
            curl -f https://google.com || exit 1
          done
