name: DEV Build/Push/Lambda-deploy

on:
  push:
    branches:
      - main

jobs:

  cognito-customize-email-lambda-build:
    uses: ./.github/workflows/lambda-image-build-push-deploy-template.yml
    with:
      app: 'cognito-customize-email-lambda'
      environment: 'development'

  cognito-customize-email-lambda-deploy:
    runs-on: ubuntu-latest
    env:
      app: cognito-customize-email-lambda
    environment:
      name: development
    needs: cognito-customize-email-lambda-build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update cognito-customize-email-lambda
        run: | 
         echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
         echo ${{ env.COMMIT_HASH }}
