name: DEV Build/Push/Lambda-deploy

on:
  push:
    branches:
      - main
jobs:


  cognito-customize-email-lambda-deploy:
    runs-on: ubuntu-latest
    env:
      app: cognito-customize-email-lambda
    environment:
      name: development
    # needs: cognito-customize-email-lambda-build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Export
        run: | 
          export VAULTS_SECRETS_DATABASE_URL=postgresql://dbo:HayXBUtEKffcG6FVEoiVDpIH4kHjXaan@che-dev-transaction-gateway.cgz7qeu1xtvk.eu-central-2.rds.amazonaws.com:5432/devtransactiongateway?schema=public

      - name: CAT
        run: |
          SECRET_VAR="VAULTS_SECRETS_DATABASE_URL"
          echo $SECRET_VAR
          export SECRET_DATA=$(env | sed -n "s/^${SECRET_VAR}\(.*\)=\(.*\)/\1: \2/p")
          echo $SECRET_DATA
          echo $VAULTS_SECRETS_DATABASE_URL
          yq e --null-input ".secrets = {\"transaction-gateway-${{ inputs.app }}-secret\": {\"data\": strenv(SECRET_DATA)}}" \
          > "secrets.transaction-gateway-api.yaml"
          cat secrets.transaction-gateway-api.yaml
        shell: bash
