name: DEV Build/Push/Deploy

on:
  push:
    branches:
      - main
jobs:

  frontend:
    uses: ./.github/workflows/build-push-deploy-template.yml
    with:
      environment: 'development'
    secrets:
      NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}