name: DEV Build/Push/Lambda-deploy

on:
  push:
    branches:
      - main
jobs:


  cognito-customize-email-lambda-deploy:
    runs-on: ubuntu-latest
    env:
      VAULTS_SECRETS_APIDATABASE_URL: po
    environment:
      name: development
    # needs: cognito-customize-email-lambda-build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # - name: Export
      #   run: | 
      #    export VAULTS_SECRETS_APIDATABASE_URL=po
      - name: CAT
        run: |
          SECRET_VAR="VAULTS_SECRETS_API"
          export SECRET_DATA=$(env | sed -n "s/^${SECRET_VAR}\(.*\)=\(.*\)/\1: \2/p")
          yq e --null-input ".secrets = {\"transaction-gateway-${{ inputs.app }}-secret\": {\"data\": strenv(SECRET_DATA)}}" \
          > "secrets.transaction-gateway-api.yaml"
          cat secrets.transaction-gateway-api.yaml
        shell: bash
