name: DEV Build/Push/Lambda-deploy

on:
  push:
    branches:
      - main

jobs:

  cognito-customize-email-lambda:
    uses: ./.github/workflows/lambda-image-build-push-deploy-template.yml
    with:
      app: 'cognito-customize-email-lambda'
      environment: 'development'
      lambda-envs: '${{ vars.COGNITO_CUSTOMIZE_EMAIL_LAMBDA }}'    
