name: DEV Build/Push/Lambda-deploy

on:
  push:
    branches:
      - main

jobs:

  # cognito-customize-email-lambda-build:
  #   uses: ./.github/workflows/lambda-image-build-push-deploy-template.yml
  #   with:
  #     app: 'cognito-customize-email-lambda'
  #     environment: 'development'

  cognito-customize-email-lambda-deploy:
    runs-on: ubuntu-latest
    env:
      app: cognito-customize-email-lambda
    environment:
      name: development
    # needs: cognito-customize-email-lambda-build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update cognito-customize-email-lambda
        run: | 
          export LAMBDA_ENVS="{\
            VAR1=${{ vars.VAR1 }},\
            VAR2=${{ vars.VAR2 }},\
            }"
          echo "Variables={ $LAMBDA_ENVS }"
