name: DEV Build/Push/Lambda-deploy

on:
  push:
    branches:
      - main
    paths:
      - 'lambdas/**'
      - '.github/workflows/ci.yml'
      - '.github/workflows/lambda-image-build-push-template.yml'

jobs:

  # cognito-customize-email-lambda-build:
  #   uses: ./.github/workflows/lambda-image-build-push-deploy-template.yml
  #   with:
  #     app: 'cognito-customize-email-lambda'
  #     environment: 'development'

  cognito-customize-email-lambda-deploy:
    runs-on: ubuntu-latest
    env:
      app: cognito-customize-email-lambda
    environment:
      name: development
    # needs: cognito-customize-email-lambda-build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update cognito-customize-email-lambda
        run: | 
          export DATABASE_URL=postgresql://dbo:HayXBUtEKffcG6FVEoiVDpIH4kHjXaan@che-dev-transaction-gateway.cgz7qeu1xtvk.eu-central-2.rds.amazonaws.com:5432/devtransactiongateway?schema=public

      - name: Create Helm Secret Files
        run: |
          yq e --null-input ".secrets = {\"transaction-gateway-api-secret\": {\"data\": strenv(DATABASE_URL)}}" \
          > "secrets.transaction-gateway-api.yaml"
          cat secrets.transaction-gateway-api.yaml
        shell: bash
