name: DEV Build/Push/Lambda-deploy

on:
  push:
    branches:
      - main

jobs:

  cognito-customize-email-lambda:
    uses: ./.github/workflows/lambda-image-build-push-deploy-template.yml
    with:
      app: 'cognito-customize-email-lambda'
      environment: 'development'
      lambda-envs: '${{ vars.COGNITO_CUSTOMIZE_EMAIL_LAMBDA }}'

  lambda-deploy:

    runs-on: ubuntu-latest
    needs: cognito-customize-email-lambda
    environment:
      name: development
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update Lambda code & environment variables
        run: |    
         echo ${{ vars.VAR1 }}
         echo  "Variables={${{ vars.VAR1 }}}"        
