name: 'Template For Docker Build, ECR Push And Helm Deploy Actions'

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      app:
        type: string
        required: true

jobs:
  prepare-anus:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Generate .env file
        run: |
          echo ${{ vars.ENV_VAR }} > ${{ secrets.env_vars }}      

  call-build-and-push:
    uses: ./.github/workflows/bp.yml
    with:
      environment: '${{ inputs.environment }}'
#    secrets:
#      env_vars: |
#        MY_NEXT_VAR: '${{ secrets.ENV_SECRET }}'
