name: 'Template For Docker Build, ECR Push And Helm Deploy Actions'

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      app:
        type: string
        required: true
    secrets:
      env_vars:
        required: true

jobs:

  call-build-and-push:
    uses: ./.github/workflows/bp.yml
    with:
      environment: '${{ inputs.environment }}'
    secrets:
      env_vars: ${{ secrets.env_vars}}
