name: 'Template For Docker Build, ECR Push And Helm Deploy Actions'

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      app:
        type: string
        required: true
#    secrets:
#      NEXT_VAR1:
#        required: true
jobs:

  call-build-and-push:
    uses: ./.github/workflows/bp.yml
    with:
      environment: '${{ inputs.environment }}'
    secrets:
      env_vars: |
        NEXT_VAR1: '${{ secrets.NEXT_VAR1}}'
        
