name: 'Template For Docker Build, ECR Push And Helm Deploy Actions'

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      app:
        type: string
        required: true
    secrets:
      ENV_SECRET:
        required: true

jobs:

  call-build-and-push:
    uses: ./.github/workflows/bp.yml
    with:
      environment: '${{ inputs.environment }}'
    secrets:
      env_vars: |
        ENV_SECRET: ${{ vars.ENV_VAR }}
