name: DEV Build/Push/Deploy

on:
  push:
    branches:
      - main1
jobs:

  frontend:
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: 'development'
      app: 'frontend'
    secrets:
      env_vars: |
        NEXT_VAR1: '${{ secrets.ENV_SECRET}}'
