name: DEV Build/Push/Deploy

on:
  push:
    branches:
      - main

env:
  VAR1: ${{ vars.ENV_VAR }}

jobs:

  frontend:
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: 'development'
      app: 'frontend'
      ENV_VAR: ${{ env.VAR1 }}
    secrets:
      ENV_SECRET: ${{ secrets.ENV_SECRET }}
