name: Development Workflow

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy-to-development:
    uses: ./.github/workflows/build-push-deploy-template.yml
    with:
      environment: 'development'
      app: 'identity-service'
      ingress-hostname: 'identity-service.dev.hashgraph-group.com'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID}}
      TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
      EKS_ENDPOINT: ${{ secrets.EKS_ENDPOINT }}
      EKS_SA_SECRET: ${{ secrets.EKS_SA_SECRET }}
