name: Test Application 🔬

on:
  workflow_call:

jobs:
  tests:
    name: Test Application 🔬
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#      - name: Set up Docker
#        uses: docker/setup-buildx-action@v2
#
#      - name: Run tests with Docker Compose
#        run: docker compose up --abort-on-container-exit

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4.2.1 # Ex: v4.1.0, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
        env:
          SONAR_HOST_URL: https://sonarqube.pub.mng.hashgraph-group.com/
          SONAR_TOKEN: squ_e33ae502ecd352c3bc10e03d41948d2c3de5c996
        with:
          args: >
            -Dsonar.projectKey=test_project_key
            -Dsonar.projectName=Test