name: Test Application 🔬

on:
  workflow_call:

jobs:
  tests:
    name: Test Application 🔬
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract branch name
        id: extract-branch
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF | awk -F/ '{print $3}')
          echo "Branch name is $BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Use branch name
        run: |
          echo "The branch name is $BRANCH_NAME"