name: Test Application 🔬

on:
  workflow_call:

jobs:
  test:
    name: Test Application 🔬
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Проверка кода
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Установка Docker и Docker Compose
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Шаг 3: Запуск Docker Compose для тестов
      - name: Run tests with Docker Compose
        run: docker-compose up --abort-on-container-exit