name: Test Application 🔬

on:
  workflow_call:

jobs:
  tests:
    name: Test Application 🔬
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Manual Trivy Setup
        uses: aquasecurity/setup-trivy@v0.2.0
        with:
          cache: true
          version: v0.57.1

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'json'
          output: 'trivy-results.json'
          severity: 'CRITICAL'
          skip-setup-trivy: true

      - name: Output Trivy results to console
        run: cat trivy-results.json

      - name: Output Trivy results as a table
        run: |
          echo "Vulnerability ID | Package | Severity | Description"
          echo "---------------- | ------- | -------- | -----------"
          jq -r '.Results[].Vulnerabilities[]? | [.VulnerabilityID, .PkgName, .Severity, .Description] | @tsv' trivy-results.json | column -t -s $'\t'