name: 'Template For Docker Build, ECR Push And Deploy Lambda'

on:
  workflow_call:

    inputs:
      environment:
        type: string
        required: false
      app:
        type: string
        required: false
   
jobs:

  Build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: BUILD ${{ inputs.app }}
        run: | 
         ls -l

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: BUILD ${{ inputs.app }}
        run: | 
         export ENVS=\
         VAR1=${{ vars.VAR1 }},\
         VAR2=${{ vars.VAR2 }}

