oname: 'Template For Docker Build, ECR Push And Deploy Lambda'

on:
  workflow_call:

    inputs:
      environment:
        type: string
        required: false
      app:
        type: string
        required: false
      lambda-envs:
        type: string
        required: false
      test:
        type: string
        required: false
   
jobs:

  Update-deploy:

    runs-on: ubuntu-latest
    needs: lambda-deploy
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update-deploy
        run: |    
         echo ${{ vars.VAR1 }}
         echo ${{ inputs.test }}
         echo  "Variables={${{ vars.VAR1 }}}"
