name: 'Template For Docker Build, ECR Push And Deploy Lambda'

on:
  workflow_call:

    inputs:
      environment:
        type: string
        required: false
      app:
        type: string
        required: false
      lambda-envs:
        type: string
        required: false
      test:
        type: string
        required: false
   
jobs:

  lambda-deploy:

    runs-on: ubuntu-latest
     
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Lambda code & environment variables
        run: |       
         echo ${{ vars.VAR1 }}
         echo ${{ inputs.test }}
         echo  "Variables={${{ inputs.lambda-envs }}}"
