name: 'Template For Docker Build, ECR Push And Deploy Lambda'

on:
  workflow_call:

    inputs:
      environment:
        type: string
        required: false
      app:
        type: string
        required: false
   
jobs:

  job1:

    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Lambda ${{ inputs.app }}
        run: | 
         export ENVS=\
         VAR1=${{ vars.VAR1 }},\
         VAR2=${{ vars.VAR2 }}
         echo $ENVS

      - name: Update Lambda ${{ inputs.app }}
        run: | 
         export ENVS=\
         VAR1=${{ vars.VAR1 }},\
         VAR2=${{ vars.VAR2 }},\
         VAR3=${{ vars.VAR2 }},
         echo $ENVS
