name: Production Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-to-production:
    uses: ./.github/workflows/build-push-deploy-template.yml
    with:
      environment: 'production'
      app: 'identity-service'
      ingress-hostname: 'identity-service.prod.hashgraphdev.com'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      VAULT_TOKEN:  ${{ secrets.VAULT_TOKEN }}
      VAULT_ADDR:  ${{ secrets.VAULT_ADDR }}
      TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID}}
      TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
      EKS_ENDPOINT: ${{ secrets.EKS_ENDPOINT }}
      EKS_SA_SECRET: ${{ secrets.EKS_SA_SECRET }}

  deploy-to-pages:
    runs-on: ubuntu-latest
    needs: deploy-to-production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build Pages
        run: npx @redocly/cli build-docs ./docs/openapi-v1.0.1.yaml -o ./docs/index.html

      - name: Deploy to GitHub Pages
        uses: actions/configure-pages@v3

      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: './docs/'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2