name: Production Workflow

on:
  push:
    branches:
      - main666
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy-to-production:
    uses: ./.github/workflows/build-push-deploy-template.yml
    with:
      environment: 'production'
      app: 'identity-service'
      ingress-hostname: 'identity-service.prod.hashgraphdev.com'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      VAULT_TOKEN:  ${{ secrets.VAULT_TOKEN }}
      VAULT_ADDR:  ${{ secrets.VAULT_ADDR }}
      TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID}}
      TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
      EKS_ENDPOINT: ${{ secrets.EKS_ENDPOINT }}
      EKS_SA_SECRET: ${{ secrets.EKS_SA_SECRET }}