name: Rollback Development ME 🔙

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Set Docker Image Tag to RollBack"
        required: true
      environment:
        description: 'choose environment'
        required: true
        type: choice
        options:
          - development
          - production
      app:
        description: 'choose app'
        required: true
        type: choice
        options:
          - identity-service
          - transaction-gateway-cli

jobs:
  rollback:
    uses: ./.github/workflows/rb-tpl.yaml
    secrets: inherit
    with:
      tag: ${{ inputs.tag }}
      environment: ${{ inputs.environment }}
      app: ${{ inputs.app }}