name: Tests Application 🔬

on:
  workflow_call:

jobs:
  tests:
    name: Test Application 🔬
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run tests with Docker Compose
        run: docker compose up --abort-on-container-exit